version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
  nginx:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
