// Whenever the user tries to login, but the email password are wrong
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const NON_EXISTENT_EMAIL = "NON_EXISTENT_EMAIL";
export const INVALID_LOGIN_METHOD_EMAIL = "INVALID_LOGIN_METHOD_EMAIL";
export const INVALID_LOGIN_METHOD_FACEBOOK = "INVALID_LOGIN_METHOD_FACEBOOK";
export const INVALID_LOGIN_METHOD_GOOGLE = "INVALID_LOGIN_METHOD_GOOGLE";
