name: Backend testing

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start test DB
        run: docker-compose --file="infra/dockers/docker-compose-postgres-test.yml" up -d

      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      - run: npm ci
        working-directory: "./backend"
      - run: npm run build
        working-directory: "./backend"
      - run: npm ci
        working-directory: "./frontend"
      - run: npm run build
        working-directory: "./frontend"
      - run: npm test
        working-directory: "./backend"
