name: Build and Push Docker Image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Photo Scorer Secrets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Set up environment
        run: echo "${{ secrets.ENV_FILE }}" > backend/.env

      - name: Set up SSL certs
        run: |
          echo "${{ secrets.NGINX_CRT }}" > ./infra/https/nginx.crt
          echo "${{ secrets.NGINX_KEY }}" > ./infra/https/nginx.key

      - name: Login to the Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag previous photoscorer tag
        run: |
          docker tag vcarp/photoscorer:latest vcarp/photoscorer:previous
          docker push vcarp/photoscorer:previous

      - name: Tag previous nginx tag
        run: |
          docker tag vcarp/photoscorer-nginx:latest vcarp/photoscorer-nginx:previous
          docker push vcarp/photoscorer-nginx:previous

      - name: Build and Push Nginx Docker image
        run: |
          docker build -t vcarp/photoscorer-nginx:latest -f infra/nginx/Dockerfile . 
          docker push vcarp/photoscorer-nginx:latest

      - name: Build and Push Docker image
        run: |
          docker build -t vcarp/photoscorer:latest -f backend/Dockerfile . 
          docker push vcarp/photoscorer:latest
