name: Build and Push Docker Image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Photo Scorer Secrets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Set up environment
        run: echo "${{ secrets.ENV_FILE }}" > backend/.env

      - name: Set up SSL certs
        run: |
          echo "${{ secrets.NGINX_CRT }}" > ./infra/https/nginx.crt
          echo "${{ secrets.NGINX_KEY }}" > ./infra/https/nginx.key

      - name: Login to the Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get the previous latest tag
        run: |
          echo "PREV_TAG=$(docker image ls vcarp/photoscorer --format "{{.Tag}}" | sort | tail -1)" >> $GITHUB_ENV

      - name: Tag previous photoscorer tag
        if: env.PREV_TAG != ''
        run: |
          docker tag vcarp/photoscorer:$PREV_TAG vcarp/photoscorer:previous
          docker push vcarp/photoscorer:previous

      - name: Get the previous latest tag nginx
        run: |
          echo "PREV_TAG_NGINX=$(docker image ls vcarp/photoscorer-nginx --format "{{.Tag}}" | sort | tail -1)" >> $GITHUB_ENV

      - name: Tag previous nginx tag
        if: env.PREV_TAG_NGINX != ''
        run: |
          docker tag vcarp/photoscorer-nginx:$PREV_TAG_NGINX vcarp/photoscorer-nginx:previous
          docker push vcarp/photoscorer-nginx:previous

      - name: Build and Push Nginx Docker image
        run: |
          docker build -t vcarp/photoscorer-nginx:latest -f infra/nginx/Dockerfile . 
          docker push vcarp/photoscorer-nginx:latest

      - name: Build and Push Docker image
        run: |
          docker build -t vcarp/photoscorer:latest -f backend/Dockerfile . 
          docker push vcarp/photoscorer:latest
